### ISSUE TITLE
Following other users

### ISSUE THREAD

**Issue by sergenassour** [noahmoryoussef/Soen341-#2]
The users will be able to follow other user accounts by a click of a button. After following a certain user, that user's new posts will be available for the follower to see in their home feed.

**Comment by sergenassour** [comment]
![Sprint1](https://user-images.githubusercontent.com/62810735/106819070-461dc780-6647-11eb-899f-8d126031ab5d.PNG)

**Comment by noahmoryoussef** [comment]
Story point estimation : 5
